mono/taglib-sharp

configure.ac

as gmcs not available in current release of mono
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>

build: use mcs instead of gmcs

---

configure.ac
src/Makefile.am
src/TagLib/Png/File.cs
src/taglib-sharp.csproj
tests/Makefile.am
tests/fixtures/TagLib.Tests.Images/PngGimpPngcrushTest.cs

SharpZipLib is used in only one place, to inflate zTXt chunks in PNG files.
DeflateStream can do the same job, without introducing a dependency
or complicating nuget packaging.
Since DeflateStream is a built-in .NET class, there is no longer a reason to
make zTXt support conditional, so I removed the conditional compilation.
Also removed a small defect in the VS project file which prevented compilation using VS.

Replace use of SharpZipLib with standard .NET DeflateStream

---

src/TagLib/Mpeg/AudioHeader.cs

... is at position 7,6 and not 15,14 as in original code.
http://www.mp3-tech.org/programmer/frame_header.html

The Channel Mode in a MPEG Audio Header

---

src/TagLib/ByteVector.cs
src/TagLib/IFD/Entries/SShortArrayIFDEntry.cs
src/TagLib/IFD/IFDReader.cs

Fixes test failures due to `OverflowException`s by adding separate signed versions of ByteVector functions with `unchecked` blocks for the binary operations.

Add signed versions of ByteVector functions

---

src/TagLib/IFD/IFDTag.cs

Some cameras (GoPro Hero 4 Black) contain GPSAltitude but not GPSAltitudeRef tag. Pull request makes GPSAltitudeRef  optional to return image Altitude.

do not require GPSAltitudeRef to return altitude

---

src/TagLib/Ape/Tag.cs
src/TagLib/Asf/Tag.cs
src/TagLib/Mpeg4/AppleTag.cs
src/TagLib/Ogg/GroupedComment.cs
tests/fixtures/TagLib.Tests.FileFormats/AiffFormatTest.cs
tests/fixtures/TagLib.Tests.FileFormats/AsfFormatTest.cs
tests/fixtures/TagLib.Tests.FileFormats/ExtendedTests.cs
tests/fixtures/TagLib.Tests.FileFormats/Id3V2FormatTest.cs
tests/fixtures/TagLib.Tests.FileFormats/M4aFormatTest.cs
tests/fixtures/TagLib.Tests.FileFormats/OggFormatTest.cs
tests/fixtures/TagLib.Tests.FileFormats/OpusFormatTest.cs
tests/tests.csproj

Added support for Replaygain Tags for Ape, Asf and MPEG4 files, including Tests

Replay gain support for Ape, Asf and Mpeg4 Files

---

src/TagLib/Aiff/File.cs

.aiff is a common extension for AIFF files, and it was missing from the TagLib.Aiff.File declaration. This PR adds it.
First noticed by https://github.com/mono/taglib/pull/20

Added the taglib/aiff (.aiff) MIME type

---

src/TagLib/Aiff/File.cs

The previous version of the AIFF file class relied on file scanning to find AIFF chunk headers, which is not reliable (see pull request https://github.com/mono/taglib-sharp/pull/20) nor fast (reading a whole AIFF file multiple times is expensive).
This PR instead implements reading of chunk headers and chunk sizes as described by the AIFF v3 standard from http://www-mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/Docs/AIFF-1.3.pdf

Fixed AIFF performance bug

---

.gitignore
src/TagLib/Mpeg/AudioHeader.cs
tests/packages.config

AudioBitrate for MPEG VBR files is calculated wrong, because the private field duration is used in the getter. duration is always zero, if the property Duration was not called before accessing AudioBitrate.

Wrong bit rate for mp3 vbr

---

README
tests/packages.config
tests/tests.csproj

This PR adds Gtk# as NuGet dependencies so Windows users only have to restore NuGet packages when opening the solution.
According to [tests/Makefile.am](https://github.com/mono/taglib-sharp/blob/master/tests/Makefile.am) this should not break testing on Linux through automake (GNOME_SHARP_LIB references the actual DLLs on Linux), but confirmation would be welcome.

Add GtkSharp to packages.config for tests

---

src/TagLib/Ogg/XiphComment.cs
tests/fixtures/TagLib.Tests.TaggingFormats/XiphTest.cs

See issue #70. This PR implements support for the now recommended `METADATA_BLOCK_PICTURE` for storing pictures in Xiph comments in Ogg Vorbis files. Pictures are loaded on-demand in the corresponding getter, and stored back to the `METADATA_BLOCK_PICTURE` when needed. The legacy `COVERART` field is supported for reading as well to provide conversion support.

[Ogg] Support for METADATA_BLOCK_PICTURE

---

src/TagLib/Riff/File.cs

I have added the changes I mentioned in the issue description. In short, for a particular WAV file where the size value is 4294967288, adding 8 overflows the variable and turns it to 0 which makes the loop infinite. 
Simply adding L to 8 explicitly makes it long and the result of 8 + size is also long. The loop stops correctly.

Fixing the issue #85 (infinite loop)

---

.travis.yml

xbuild is slowly getting deprecated in favor for the official msbuild
tool which has since been open sourced.

Switch from xbuild to msbuild.

---

src/TagLib/Matroska/Tag.cs

fix `ArgumentNullException `in `string.Join("; ", list)`, when `list == null`

fix ArgumentNullException

---

debug/Program.cs
debug/debug.csproj
src/TagLib/Matroska/File.cs
src/TagLib/Matroska/Tags.cs

This contains an improved handling of corrupted (truncated) Matroska files.
When a incomplete Matroska file is read by TagLib#, the following behavior is changed:
- Returns a Corrupted file instead of issuing an exception
- Best effort done to retrieve data at the begining of the file (like properties)
- As a result, a `TagLib.File.Create` will most of the time return something, but the returned object may be marked as corrupted.

Mkv crachfix

---

.travis.yml
tests/MainWindow.cs
tests/packages.config
tests/tests.csproj

This updates the Nunit package to NUnit v3.10.1, and restore the Visual Studio Nunit 3 Test Adapter nugget. This re-enables the Nunit tests to be run in Visual Studio, as this has been broken in the transition to .Net framework 2.0.

Nunit update

---

src/TagLib/Riff/File.cs

This addresses #101.
TagLib# does not handle reading a chunk when the position value is odd.  Having a chunk with an odd size before the data chunk forces TagLib# to never read the data chunk. Therefore the duration is never calculated as well as some other members are not populated.
This PR fixes this by checking if the chunk is odd and increments the position by one byte.

Added fix for chunks with odd-sized lengths

---

README.md
src/TagLib/Id3v2/Frames/AttachmentFrame.cs
src/TagLib/Mpeg/AudioHeader.cs
src/TagLib/PictureLazy.cs
src/TagLib/Riff/AviHeaderList.cs

After enabling my project to run TagLib# more extensively on on my video collection, I spotted a few new corner-cases where we could trigger a null-reference exception. Also integrated issues #116 and #119.
- Updated GitHub front-page for TagLib# as discussed in #116
You can see how it looks like at: https://github.com/Starwer/taglib-sharp/tree/miscfix_doc
- Fixed wrong duration issue as reported in #119;
- Fixed null reference exceptions in different spots;

Misc fixes and front-page documentation

---

src/TagLib/Mpeg4/BoxHeader.cs

Fixes the Box header exception format to pass parameters correctly instead of `{0}` and `{1}`

Fixed: Mpeg4 Box Header Exception Format

---

src/TagLib/Mpeg/AudioHeader.cs

This fix avoids a stack overflow when a file with broken headers is being read.

Fixes #84: MP3 File with broken headers create a Stack Overflow

---

src/TagLib/Matroska/File.cs

According to the specifications Top Level elements should include a CRC-32 element as a child segment. (http://matroska-org.github.io/matroska-specification/ordering.html)
A SeekHead is a top level element (https://matroska.org/technical/specs/index.html)
This patch handles a CRC-32 element if found in a SeekHead, don't return false otherwise the SeekHead is marked a corrupted and metadata is never written to the file while saving.
@Starwer can you please review this

[Matroska] Handle CRC-32 element in SeekHead instead of marking it Corrupt

---

src/TaglibSharp/IFD/IFDReader.cs

Images taken with an Olympus camera don't have data in the expected
format at the expected location. This change prevents the crash we
got previously by ignoring the OverflowException.

Do not crash if there is an overflow error reading tag data

---

taglib-sharp.pc.in

This brings back pkg-config support by re-adding the .pc.in file. Users can change the prefix and version parameters accordingly via `sed`. Fixes #171.

re-add pkg-config support

---

README.md
appveyor.yml

This fixes AppVeyor from the Core 3.1 change, too
Otherwise, just some notes about different menus in VS 2019

update Readme, AppVeyor to 2019

---

README.md

Added a brief section to README for explicate reference to latest nuget package, as there is some ambiguity as to what the latest official package is.  This is referenced in issue #192.

Added nuget reference to README.md

---

src/TaglibSharp.Tests/FileFormats/Id3V2FormatTest.cs
src/TaglibSharp/Tag.cs

Ensures that `Pictures` on the `Id3v2` object are copied over to the `File.Tag` on a `CopyTo` operation.

Fixes #200 and copies Pictures over from Id3v2 Tag to File.Tag

---

src/TaglibSharp.Tests/TaggingFormats/Id3V2Test.cs
src/TaglibSharp/Id3v2/FrameFactory.cs
src/TaglibSharp/Id3v2/FrameTypes.cs

This change adds support for the IPLS frame in ID3 V 2.3
In ID3 V2.4 this is the TIPL frame and supported ootb

Added support for IPLS Frame

---

src/TaglibSharp.Tests/FileFormats/OpusFormatTest.cs
src/TaglibSharp/Ogg/Bitstream.cs
src/TaglibSharp/Ogg/PageHeader.cs

There is a corruption bug in OPUS file writer, see https://github.com/mono/taglib-sharp/issues/221
The root cause is that the Ogg `Bitstream` class assumes that the final packet of any page is incomplete, and so reads the next page (the first media page) and looks at the `PageFlag.FirstPacketContinued` flag to determine what to do.  This means it's marking the first media page as part of the "variant" section and rewriting it i.e. `InvariantStartPosition` is one page later than it should be.  
When it re-writes the first media page, it generates a new `Page` and `PageHeader` with the `AbsoluteGranualarPosition` set to `0`, but this is not allowed in an Opus media page - it should be:
> the total number of PCM samples in the stream up to and including the last fully decodable sample from …

Fixed: Corrupting OPUS files on write

---

src/TaglibSharp/Matroska/File.cs

The readme says that webm audio files are supported, however trying to load them produces a FileNotSupported exception. i.e. open audio.webm
Adding taglib/webm allows the file to be opened and tags be written to the file.

Add support for webm audio files

---

src/TaglibSharp/Id3v2/Tag.cs

Some applications write the MusicBrainz Tags as "MUSICBRAINZ ARTIST ID"
The current implementtation does a case sensitive lookup for "MusicBrainz Artist Id", which means we don't get frames for that altough they are really there.

MusicBrainz Tags should be retrieved case insensitive

---

src/TaglibSharp/Id3v2/Tag.cs

With that change it is possibe for application, which make use of Taglib-sharp, to write TXXX frames.
Currently these methods can only be used internally, e.g. for setting the ReplayGain Frames

Make methods SetUserTextAsString public

---

src/TaglibSharp/Id3v2/Tag.cs

Fixes https://github.com/mono/taglib-sharp/issues/166, please look there for the reasons behind this change.

Add format to TrackCount setter

---

src/TaglibSharp.Tests/FileFormats/AsfFormatTest.cs
src/TaglibSharp/Asf/FilePropertiesObject.cs
src/TaglibSharp/Asf/HeaderObject.cs

**Description**: Another couple bugs I found while porting ASF support in TagLib# to node 😅
The TagLib# implementation of ASF duration wasn't calculating the same duration for the sample.wma file as FFMpeg, foobar2000, VLC, which all said the file was 0:04 (or 4.153s). TagLib# was reporting the file was around 5s. Digging through the [ASF specification](https://hwiegman.home.xs4all.nl/fileformats/asf/ASF_Specification.pdf) and reading the sample with a hex editor, I found two issues with the TagLib# implementation:
1) The ASF File Properties Object (page 14 in the linked PDF) stores the play duration *before* the send duration. TagLib# is reading/writing the object the other way around, which means duration was calculated based on send duration (which in this case is a hundred …

ASF Duration Calculation Fix, Creation Date Fix

---

src/TaglibSharp.Tests/FileFormats/Id3BothFormatTest.cs
src/TaglibSharp/Mpeg/AudioFile.cs

Introduced a property to omit auto creation of non-existing Id3v1 and Id3v2 Tag Types as per issue #251.

Property preventing autocreate id3 tag types

---

src/TaglibSharp.Tests/FileFormats/MpgFormatTest.cs
src/TaglibSharp/Mpeg/File.cs

**Description**: While working on my port of TagLib# to node, I added a test case to validate that the Turning Lime sample video was being decoded with the correct audio properties. I noticed that the audio bitrate wasn't decoded correctly compared to output from FFMpeg. With some help from http://andrewduncan.net/mpeg/mpeg-1.html and some digging in a hex editor, I figured out that the original implementation assumes there is always 16 "stuffing bytes" before the packet data begins. In the case of the turning lime file, there aren't any stuffing bytes (always 0xFF), so when the audio header is searched for, the correct header is skipped over and something that kinda looks like an audio header (ie, starts with 0xFF, >=0xE0) is decoded instead. This returns an audio bitrate of 192 instead …

MPEG Audio Header Offset Calculation

---

src/TaglibSharp/Aiff/StreamHeader.cs
src/TaglibSharp/ByteVector.cs

**Description**: During my port of taglib# to node, I noticed a long string of logic for determining the sample rate for AIFF files. Since it's not uncommon for sample rates to be stored in a table, I didn't think much of it. However, while working on writing unit tests for the `Aiff.StremHeader` class, I wanted to double check the AIFF spec to see if there were any more sample rates, since it seemed odd that AIFF could only support a max sample rate of 64kHz when 96kHz and 192kHz files are all the rage these days. Turns out the AIFF spec uses an 80-bit IEEE 754 extended precision floating point number for storing the sample rate (http://muratnkonar.com/aiff/index.html), not a lookup table of sample rates. What's more, I've seen Apple users mention that 96kHz AIFF files exist …

Adding extended precision ByteVector conversion for AIFF sample rate

---

src/TaglibSharp/ByteVector.cs
src/TaglibSharp/Id3v2/FrameFactory.cs
src/TaglibSharp/Id3v2/FrameTypes.cs
src/TaglibSharp/Id3v2/Frames/ChapterFrame.cs
src/TaglibSharp/Id3v2/Frames/TableOfContentsFrame.cs

Hi. This is sort of rudimentary. Ideally I would like to expose the chapters directly from the File’s Tag property and have TagLib handle the internals like generating ids and enforcing uniqueness, but it’s been working fine for me going through `(TagLib.Id3v2.Tag)File.GetTag(TagLib.TagTypes.Id3v2)` and setting the frames up manually.

Added support for chapters by implementing the frames CHAP and CTOC

---

src/TaglibSharp/Xmp/XmpTag.cs

A `TAGLIB# DEBUG: Added ns1 prefix for...` line is written to the console when XMP tags are encountered. This is seemingly a leftover debug line and cannot be turned off, interfering with software that uses the standard output to write data.

Remove TAGLIB# DEBUG line when reading XMP tags

---

src/TaglibSharp.Tests/TaggingFormats/Id3V2Test.cs
src/TaglibSharp/Id3v2/FrameFactory.cs
src/TaglibSharp/Id3v2/FrameHeader.cs
src/TaglibSharp/Id3v2/FrameTypes.cs
src/TaglibSharp/Id3v2/Frames/TextIdentificationFrame.cs

feat(id3): support apple MVNM/MVIN frame

---

src/TaglibSharp/Xmp/XmpTag.cs

A `TAGLIB# DEBUG: Added ns1 prefix for...` line is written to the console when XMP tags are encountered. This is seemingly a leftover debug line and cannot be turned off, interfering with software that uses the standard output to write data.

Remove TAGLIB# DEBUG line

---

.github/workflows/ubuntu.yml
src/TaglibSharp.Tests/FileFormats/M4aFormatTest.cs
src/TaglibSharp.Tests/TaggingFormats/ApeTest.cs
src/TaglibSharp.Tests/TaggingFormats/AsfTest.cs
src/TaglibSharp.Tests/TaggingFormats/Id3V2Test.cs
src/TaglibSharp.Tests/TaggingFormats/Mpeg4Test.cs
src/TaglibSharp.Tests/TaggingFormats/XiphTest.cs
src/TaglibSharp/Ape/Tag.cs
src/TaglibSharp/Asf/Tag.cs
src/TaglibSharp/CombinedTag.cs
src/TaglibSharp/Id3v2/Tag.cs
src/TaglibSharp/Mpeg4/AppleTag.cs
src/TaglibSharp/Ogg/GroupedComment.cs
src/TaglibSharp/Ogg/XiphComment.cs
src/TaglibSharp/Tag.cs

This PR adds two new MusicBrainz tags and fixes one MusicBrainz tag that used the wrong frame.
- Fixes #304
- Add MusicBrainzRecordingId
- Add MusicBrainzWorkId
This basically means the following:
MusicBrainzRecordingId returns the value that was previously returned by MusicBrainzTrackId.
MusicBrainzTrackId now returns the correct frame data.
MusicBrainzWorkId added to return its frame data.
I used the following documentation: https://picard-docs.musicbrainz.org/downloads/MusicBrainz_Picard_Tag_Map.html

Enhancements and Fixes for MusicBrainz Integration

---

src/TaglibSharp/Ape/Item.cs

Some applications still use APE v1 tags (such as Station Playlist, which is used by a lot of radio stations).
APE v1 does not use flags. Because of this, Taglib treats binary tags which were written by an application that uses APE v1 as strings. Even if it is really binary data.
This change fills both the data and text fields of an APE item.
The "normal flow" reading the text-field, because Type is still set to ItemType.Text.
However if the application knows that the item is really binary, it will be able to read it by setting Type to ItemType.Binary.

Added workaround for APE v1 where binary tags are treated as string

---

src/TaglibSharp/IFD/IFDReader.cs

Hi!
By testing the taglib-sharp by multi-thread processing the bunch of jpgs I've encountered the unhandled KeyNotFoundException.
I've found and fixed the bug - added synchronization locks to protect ifd_offsets and ifd_loopdetect_refs from being modified from multiple thread simultaneously.
and tested the lib again.
It works correctly on my side now.
Would you like to merge this bugfix into the master?

Fixed KeyNotFoundException in IFDReader
